version: '3'

volumes:
  postgres_tenant_data:
    driver: local

services:
  tenantdb:
    image: postgres:13-alpine
    volumes:
      - postgres_tenant_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tenantdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
